Repository jenkins-x/terraform-google-jx, pull requests merged in 2020-08, with the labels that each got.

#125 feat: enable Kubernetes Engine API
  main.tf
Labels: approved, lgtm, size/XS

#127 fix: check if tuples are empty
  modules/cluster/outputs.tf
  modules/vault/main.tf
Labels: approved, lgtm, size/M

#129 fix: add recursive flag to terraform fmt
  .gitignore
  Makefile
  examples/additional-nodepool/main.tf
  examples/basic/main.tf
  modules/backup/main.tf
  modules/backup/outputs.tf
  modules/backup/variables.tf
  modules/cluster/main.tf
  modules/cluster/serviceaccount.tf
  modules/cluster/storage.tf
  modules/cluster/variables.tf
  modules/dns/main.tf
  modules/dns/variables.tf
  modules/vault/outputs.tf
  modules/vault/variables.tf
Labels: approved, lgtm, size/L

#134 chore: add ankitm123 and MarckK to the OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#132 feat: Add support for preemptible node
  README.md
  examples/preemptible/main.tf
  main.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/S

#137 fix: disable namespace and sa creation for jx3
  main.tf
  modules/backup/main.tf
  modules/backup/variables.tf
  modules/dns/main.tf
Labels: approved, lgtm, size/S
