Repository jenkins-x/terraform-google-jx, pull requests merged in 2020-06, with the labels that each got.

#94 feat: allow to specify cluster location as zone or region
  README.md
  examples/additional-nodepool/main.tf
  main.tf
  modules/backup/variables.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  modules/vault/variables.tf
  output.tf
  scripts/ci.sh
  spec/k8s_spec.sh
  variables.tf
Labels: approved, lgtm, size/M

#99 feat: allow configuration of bucket location via bucket_location variable
  README.md
  main.tf
  modules/backup/main.tf
  modules/backup/variables.tf
  modules/cluster/storage.tf
  modules/cluster/variables.tf
  modules/vault/main.tf
  modules/vault/variables.tf
  variables.tf
Labels: approved, lgtm, size/M

#103 feat: make resource creation for backup/velero optional
  README.md
  main.tf
  modules/backup/main.tf
  modules/backup/outputs.tf
  modules/backup/variables.tf
  modules/jx-requirements.yml.tpl
  scripts/ci.sh
  variables.tf
Labels: approved, size/M

#107 feat: introducing vault_url variable to configure external Jenkins X system Vault
  README.md
  main.tf
  modules/jx-requirements.yml.tpl
  modules/vault/main.tf
  modules/vault/outputs.tf
  modules/vault/variables.tf
  variables.tf
Labels: approved, lgtm, ready for review, size/L

#111 Allow specifying disk type
  README.md
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, lgtm, ok-to-test, size/S

#106 feat: use cluster autoscaler to improve deploy time
  modules/cluster/main.tf
  modules/cluster/serviceaccount.tf
  modules/cluster/variables.tf
Labels: approved, lgtm, size/M

#120 fix: making sure usage examples specifiy the jx_requirements output
  README.md
  examples/backend-encrypted/main.tf
  examples/backend/main.tf
  examples/basic/main.tf
Labels: size/M
