Repository jenkins-x/terraform-google-jx, pull requests merged in 2020-10, with the labels that each got.

#145 feat: disable legacy auth by default
  modules/cluster/variables.tf
Labels: approved, lgtm, ok-to-test, size/XS

#150 fix: enable ui SA by default
  variables.tf
Labels: approved, size/XS

#151 chore: fix terraform 0.13.4 linting issues
  main.tf
Labels: approved, lgtm, size/XS

#152 chore: lets output the tekton service account that was used so further IAM bindings can be added in parent modules
  modules/cluster/main.tf
  modules/cluster/outputs.tf
  output.tf
Labels: approved, lgtm, size/S
