Repository jenkins-x/terraform-google-jx, pull requests merged in 2020-05, with the labels that each got.

#76 fix: always create DNS related namespaces
  modules/dns/main.tf
Labels: size/S

#77 fix: adding note to README about use of jx-requirements.yml
  README.md
Labels: size/S

#83 fix: widen version scope for local provider
  main.tf
Labels: approved, lgtm, size/XS

#86 chore: Switch to Lighthouse as default webhook provider
  README.md
  variables.tf
Labels: approved, lgtm, size/XS

#89 fix: widen version scope for all providers
  main.tf
Labels: approved, lgtm, size/XS

#91 chore: add example for additional node pools
  examples/additional-nodepool/main.tf
Labels: approved, lgtm, ok-to-test, size/M
