Repository jenkins-x/terraform-google-jx, pull requests merged in 2020-04, with the labels that each got.

#55 fix: issue with 400 Bad Request errors
  main.tf
Labels: approved, lgtm, ok-to-test, size/XS

#54 fix: using random pet name to chose cluster name if not explicitly set
  README.md
  main.tf
  output.tf
  variables.tf
Labels: approved, lgtm, size/M

#57 fix: making sure to use right variable for path to template file
  main.tf
Labels: lgtm, size/XS

#59 fix: generating jx-requirements.yml opposed to jx-requirements.yaml
  .gitignore
  README.md
  main.tf
  modules/jx-requirements.yml.tpl
  scripts/ci.sh
  spec/gcloud_spec.sh
  spec/jx_requirements_spec.sh
  spec/k8s_spec.sh
  variables.tf
Labels: approved, lgtm, size/M

#63 chore: Add daveconde to owners
  OWNERS
Labels: approved, lgtm, size/XS

#69 fix: adding resource_labels variable to allow creation of cluster labels
  README.md
  main.tf
  modules/backup/main.tf
  modules/backup/variables.tf
  modules/cluster/main.tf
  modules/cluster/serviceaccount.tf
  modules/cluster/variables.tf
  modules/dns/main.tf
  modules/dns/variables.tf
  modules/vault/main.tf
  modules/vault/variables.tf
  output.tf
  scripts/ci.sh
  spec/k8s_spec.sh
  variables.tf
Labels: approved, lgtm, size/L

#64 fix: always render ingress section in jx-requirements.yml
  README.md
  main.tf
  modules/cluster/storage.tf
  modules/jx-requirements.yml.tpl
  output.tf
  scripts/ci.sh
  spec/jx_requirements_spec.sh
  variables.tf
Labels: approved, lgtm, size/M
