Repository jenkins-x/terraform-google-jx, pull requests merged in 2020-11, with the labels that each got.

#153 chore: when jx3 lets bind to correct named external dns k8s sa
  modules/dns/main.tf
Labels: approved, lgtm, size/S

#154 feat: jx3 install health components once cluster has been created
  modules/cluster/main.tf
Labels: approved, lgtm, size/S

#156 feat: allow terraform to manage DNS zones and support specifying a su…
  main.tf
  modules/cluster/main.tf
  modules/dns/main.tf
  modules/dns/outputs.tf
  modules/dns/variables.tf
  modules/jx-requirements.yml.tpl
  output.tf
  variables.tf
Labels: approved, lgtm, size/L

#158 fix: make subdomain optional
  variables.tf
Labels: approved, lgtm, ok-to-test, size/XS

#160 chore: add latest machine types from GCP docs
  modules/cluster/variables.tf
Labels: approved, lgtm, ok-to-test, size/L
