Repository jenkins-x/terraform-google-jx, pull requests merged in 2021-01, with the labels that each got.

#168 chore: update tf version to work for 0.14
  main.tf
Labels: approved, lgtm, size/XS

#171 feat: optinally disable kuberhealthy install and set requirement to i…
  README.md
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  modules/jx-requirements.yml.tpl
  variables.tf
Labels: approved, lgtm, size/S

#174 fix: limit kubernetes provider to ~>1.11.0
  main.tf
Labels: approved, lgtm, ok-to-test, size/XS
