Repository jenkins-x/terraform-google-jx, pull requests merged in 2022-06, with the labels that each got.

#216 fix: flip conditionals for installing kuberhealthy
  .gitignore
  modules/cluster/main.tf
Labels: lgtm, size/XS

#215 fix: remove versions from provider block
  Makefile
  OWNERS
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  modules/vault/main.tf
  variables.tf
Labels: size/M

#218 Adjust resources for tekton 28
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/S

#219 Upgrade pipline
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/XS

#197 feat: optional minimal private cluster configuration
  README.md
  examples/private-nodes/main.tf
  main.tf
  modules/cluster/firewall.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: ok-to-test, size/L

#220 feat: upgrade gcp tf provider to 4+
  .terraform.lock.hcl
  main.tf
  modules/backup/main.tf
  modules/cluster/main.tf
  modules/cluster/serviceaccount.tf
  modules/dns/main.tf
  modules/gsm/main.tf
  modules/vault/main.tf
Labels: approved, size/L

#221 fix: add option to enable spot instances
  README.md
  main.tf
  modules/cluster/main.tf
  modules/cluster/variables.tf
  variables.tf
Labels: approved, size/M
